name: LiteMotto
version: 4.0.0
main: org.baicaizhale.litemotto.LiteMotto
api-version: 1.18
description: 一个在玩家加入游戏时发送格言的插件
author: baicaizhale & zip8919

commands:
  litemotto:
    description: LiteMotto 插件命令
    usage: |
      /litemotto gen - 生成一条格言并发送给执行者
      /litemotto debug - 切换调试模式
      /litemotto reload - 重载插件配置
      /litemotto update - 检查插件更新
permissions:
  litemotto.gen:
    description: 允许玩家生成格言
    default: op
  litemotto.debug:
    description: 允许玩家切换调试模式
    default: op
  litemotto.reload:
    description: 允许玩家重载 LiteMotto 插件配置
    default: op
  litemotto.update:
    description: 允许玩家检查插件更新
    default: op