name: Publish Package

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 从 git tag 获取版本号
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set version
        run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dversion=$VERSION

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: litemotto-package
          path: target/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: litemotto-package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            litemotto-package/*
          draft: false
          prerelease: false